import { NodeSourceLocation } from '../../runescipt-parser/ast/NodeSourceLocation';
import { Opcode } from './Opcode';

/**
 * Represents a single code instruction generated by the code generator.
 */
export class Instruction<T> {
    constructor(
        public readonly opcode: Opcode<T>,
        public readonly operand: T,
        public readonly source?: NodeSourceLocation
    ) {}

    public deconstruct(): [Opcode<T>, T] {
        return [this.opcode, this.operand];
    }

    public toString(): string {
        return `Instruction(opcode=${this.opcode}, operand=${this.operand})`;
    }
}